// Copyright 2023 Ellucian Company L.P. and its affiliates.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable CS1591

namespace Ellucian.Colleague.Api.Resources
{

    public sealed class AdminResources
    {
        public const string CacheManagerErrorKeyNotFound = "CacheManagerErrorKeyNotFound";
    }

    public sealed class Finance
    {
        public sealed class StatementResources
        {
            public const string DateGeneratedText = "DateGeneratedText";
            public const string DepositsDueNote = "DepositsDueNote";
            public const string Label_AmountDue = "Label_AmountDue";
            public const string Label_AmountPaid = "Label_AmountPaid";
            public const string Label_Charges = "Label_Charges";
            public const string Label_CourseSchedule = "Label_CourseSchedule";
            public const string Label_Deposits = "Label_Deposits";
            public const string Label_DepositsAppliedAmount = "Label_DepositsAppliedAmount";
            public const string Label_DepositsDate = "Label_DepositsDate";
            public const string Label_DepositsDepositAmount = "Label_DepositsDepositAmount";
            public const string Label_DepositsDepositId = "Label_DepositsDepositId";
            public const string Label_DepositsDepositType = "Label_DepositsDepositType";
            public const string Label_DepositsDue = "Label_DepositsDue";
            public const string Label_DepositsDueAmount = "Label_DepositsDueAmount";
            public const string Label_DepositsDueBalance = "Label_DepositsDueBalance";
            public const string Label_DepositsDueDate = "Label_DepositsDueDate";
            public const string Label_DepositsDueId = "Label_DepositsDueId";
            public const string Label_DepositsDuePaid = "Label_DepositsDuePaid";
            public const string Label_DepositsDueTerm = "Label_DepositsDueTerm";
            public const string Label_DepositsDueType = "Label_DepositsDueType";
            public const string Label_DepositsOtherAmounts = "Label_DepositsOtherAmounts";
            public const string Label_DepositsRefundAmount = "Label_DepositsRefundAmount";
            public const string Label_DepositsRemainingAmount = "Label_DepositsRemainingAmount";
            public const string Label_DepositsTerm = "Label_DepositsTerm";
            public const string Label_DetailHeader = "Label_DetailHeader";
            public const string Label_DueDate = "Label_DueDate";
            public const string Label_Fees = "Label_Fees";
            public const string Label_FeesAmount = "Label_FeesAmount";
            public const string Label_FeesDescription = "Label_FeesDescription";
            public const string Label_FeesTerm = "Label_FeesTerm";
            public const string Label_FinancialAid = "Label_FinancialAid";
            public const string Label_FinancialAidAnticipatedAmount = "Label_FinancialAidAnticipatedAmount";
            public const string Label_FinancialAidAwardDescription = "Label_FinancialAidAwardDescription";
            public const string Label_FinancialAidAwardedAmount = "Label_FinancialAidAwardedAmount";
            public const string Label_FinancialAidComments = "Label_FinancialAidComments";
            public const string Label_FinancialAidCurrentlyIneligible = "Label_FinancialAidCurrentlyIneligible";
            public const string Label_FinancialAidDisbursedAmount = "Label_FinancialAidDisbursedAmount";
            public const string Label_FinancialAidLoanFee = "Label_FinancialAidLoanFee";
            public const string Label_FinancialAidOtherTerms = "Label_FinancialAidOtherTerms";
            public const string Label_FinancialAidTerm = "Label_FinancialAidTerm";
            public const string Label_FutureBalance = "Label_FutureBalance";
            public const string Label_Other = "Label_Other";
            public const string Label_OtherAmount = "Label_OtherAmount";
            public const string Label_OtherBalance = "Label_OtherBalance";
            public const string Label_OtherDate = "Label_OtherDate";
            public const string Label_OtherDescription = "Label_OtherDescription";
            public const string Label_OtherInvoiceId = "Label_OtherInvoiceId";
            public const string Label_OtherTerm = "Label_OtherTerm";
            public const string Label_PaymentPlans = "Label_PaymentPlans";
            public const string Label_PaymentPlansAmountDue = "Label_PaymentPlansAmountDue";
            public const string Label_PaymentPlansAmountPaid = "Label_PaymentPlansAmountPaid";
            public const string Label_PaymentPlansCurrentBalance = "Label_PaymentPlansCurrentBalance";
            public const string Label_PaymentPlansCurrentDue = "Label_PaymentPlansCurrentDue";
            public const string Label_PaymentPlansDatePaid = "Label_PaymentPlansDatePaid";
            public const string Label_PaymentPlansDisclaimerText = "Label_PaymentPlansDisclaimerText";
            public const string Label_PaymentPlansDueDate = "Label_PaymentPlansDueDate";
            public const string Label_PaymentPlansId = "Label_PaymentPlansId";
            public const string Label_PaymentPlansLateCharge = "Label_PaymentPlansLateCharge";
            public const string Label_PaymentPlansNetAmountDue = "Label_PaymentPlansNetAmountDue";
            public const string Label_PaymentPlansOriginalAmount = "Label_PaymentPlansOriginalAmount";
            public const string Label_PaymentPlansSetupCharge = "Label_PaymentPlansSetupCharge";
            public const string Label_PaymentPlansTerm = "Label_PaymentPlansTerm";
            public const string Label_PaymentPlansType = "Label_PaymentPlansType";
            public const string Label_Payments = "Label_Payments";
            public const string Label_PaymentsAmount = "Label_PaymentsAmount";
            public const string Label_PaymentsDate = "Label_PaymentsDate";
            public const string Label_PaymentsPaymentId = "Label_PaymentsPaymentId";
            public const string Label_PaymentsPayMethod = "Label_PaymentsPayMethod";
            public const string Label_PaymentsReferenceNumber = "Label_PaymentsReferenceNumber";
            public const string Label_PaymentsTerm = "Label_PaymentsTerm";
            public const string Label_PreviousBalance = "Label_PreviousBalance";
            public const string Label_Refunds = "Label_Refunds";
            public const string Label_RefundsAmount = "Label_RefundsAmount";
            public const string Label_RefundsDate = "Label_RefundsDate";
            public const string Label_RefundsDescription = "Label_RefundsDescription";
            public const string Label_RefundsPayMethod = "Label_RefundsPayMethod";
            public const string Label_RefundsTerm = "Label_RefundsTerm";
            public const string Label_RefundsVoucherId = "Label_RefundsVoucherId";
            public const string Label_RoomAndMeals = "Label_RoomAndMeals";
            public const string Label_RoomAndMealsAmount = "Label_RoomAndMealsAmount";
            public const string Label_RoomAndMealsDate = "Label_RoomAndMealsDate";
            public const string Label_RoomAndMealsDescription = "Label_RoomAndMealsDescription";
            public const string Label_RoomAndMealsRoom = "Label_RoomAndMealsRoom";
            public const string Label_RoomAndMealsTerm = "Label_RoomAndMealsTerm";
            public const string Label_ScheduleCeu = "Label_ScheduleCeu";
            public const string Label_ScheduleCourse = "Label_ScheduleCourse";
            public const string Label_ScheduleCredits = "Label_ScheduleCredits";
            public const string Label_ScheduleDates = "Label_ScheduleDates";
            public const string Label_ScheduleDays = "Label_ScheduleDays";
            public const string Label_ScheduleDescription = "Label_ScheduleDescription";
            public const string Label_ScheduleRooms = "Label_ScheduleRooms";
            public const string Label_ScheduleTerm = "Label_ScheduleTerm";
            public const string Label_ScheduleTimes = "Label_ScheduleTimes";
            public const string Label_Sponsorships = "Label_Sponsorships";
            public const string Label_SponsorshipsAmount = "Label_SponsorshipsAmount";
            public const string Label_SponsorshipsSponsorDescription = "Label_SponsorshipsSponsorDescription";
            public const string Label_SponsorshipsSponsorshipId = "Label_SponsorshipsSponsorshipId";
            public const string Label_SponsorshipsTerm = "Label_SponsorshipsTerm";
            public const string Label_StudentId = "Label_StudentId";
            public const string Label_StudentName = "Label_StudentName";
            public const string Label_SummaryBalance = "Label_SummaryBalance";
            public const string Label_SummaryDepositsDue = "Label_SummaryDepositsDue";
            public const string Label_SummaryPageHeader = "Label_SummaryPageHeader";
            public const string Label_SummaryPayPlanAdjustments = "Label_SummaryPayPlanAdjustments";
            public const string Label_TotalBalance = "Label_TotalBalance";
            public const string Label_TuitionBySection = "Label_TuitionBySection";
            public const string Label_TuitionBySectionCeu = "Label_TuitionBySectionCeu";
            public const string Label_TuitionBySectionCredits = "Label_TuitionBySectionCredits";
            public const string Label_TuitionBySectionDescription = "Label_TuitionBySectionDescription";
            public const string Label_TuitionBySectionSectionId = "Label_TuitionBySectionSectionId";
            public const string Label_TuitionBySectionStatus = "Label_TuitionBySectionStatus";
            public const string Label_TuitionByTotal = "Label_TuitionByTotal";
            public const string Label_TuitionByTotalCeu = "Label_TuitionByTotalCeu";
            public const string Label_TuitionByTotalCredits = "Label_TuitionByTotalCredits";
            public const string Label_TuitionByTotalDescription = "Label_TuitionByTotalDescription";
            public const string Label_TuitionByTotalSectionId = "Label_TuitionByTotalSectionId";
            public const string Label_TuitionByTotalStatus = "Label_TuitionByTotalStatus";
            public const string Label_TuitionByTotalTerm = "Label_TuitionByTotalTerm";
            public const string OverdueText = "OverdueText";
            public const string RemittanceLineText = "RemittanceLineText";
            public const string Label_TuitionBySectionAmount = "Label_TuitionBySectionAmount";
            public const string Label_TuitionBySectionTerm = "Label_TuitionBySectionTerm";
            public const string DisclosureStatement = "DisclosureStatement";
            public const string Label_RefundsReferenceNumber = "Label_RefundsReferenceNumber";
            public const string Label_RefundsTransactionNumber = "Label_RefundsTransactionNumber";
            public const string CurrentAmountDue_DueText = "CurrentAmountDue_DueText";
            public const string Label_AmountOverdue = "Label_AmountOverdue";
            public const string Label_CurrentAmountDue = "Label_CurrentAmountDue";
        }
    }
    public sealed class HumanResources
    {
        public sealed class BenefitsEnrollment
        {
            public const string Benefits_ConfirmationText = "Benefits_ConfirmationText";
            public const string ReportHeader_Title = "ReportHeader_Title";
            public const string Report_Header_TitleDescription = "Report_Header_TitleDescription";
            public const string TableHeader_Benefit = "TableHeader_Benefit";
            public const string TableHeader_BenefitPlan = "TableHeader_BenefitPlan";
            public const string TableHeader_CoverageOrParticipation = "TableHeader_CoverageOrParticipation";
            public const string TableHeader_DependentsOrBeneficiaries = "TableHeader_DependentsOrBeneficiaries";
            public const string TableHeader_HealthCareProvider = "TableHeader_HealthCareProvider";
        }
    }
}
#pragma warning restore CS1591
